### PR TITLE
Fix#38: Ensures proper pairing of tool messages

### LINKED ISSUE #38: Invalid parameter: messages with role 'tool' must be a response to a preceeding message with 'tool_calls'.
"convex": "^1.23.0"
"@convex-dev/agent": "0.0.15-alpha.2"

When using `includeToolCalls: true` in `contextOptions`, tool calls are not correctly setup.

```
data: {
    error: {
      message: "Invalid parameter: messages with role 'tool' must be a response to a preceeding message with 'tool_calls'.",
      type: 'invalid_request_error',
      param: 'messages.[8].role',
      code: null
    }
  },
```

This is an interesting topic where I have a few questions. Let's take the following example:
```ts
const agentInstance = new Agent(components.agent, {
    name: "Agent",
    instructions,
    maxSteps: 10,
    tools,
    chat: openai.languageModel("gpt-4.1-mini"),
    textEmbedding: openai.embedding("text-embedding-3-small"),
    contextOptions: {
      recentMessages: 10,
      includeToolCalls: true,
      searchOtherThreads: false,
      searchOptions: {
        limit: 3,
        messageRange: { before: 2, after: 2 },
        textSearch: false,
        vectorSearch: true,
      },
    },
  });
```
I declared that I want the 10 most recent messages kept in my content.
1. Do tools count towards the 10 messages?
2. I declared `includeToolCalls` inside my `contextOptions`, not my `searchOptions`. Are old tool calls retrieved by text/vector search?

I believe the answers should be:
1. No - or configurable. I know that tool calls can eat up a lot (if not most) of context in many cases but the bottom line is that they are not messages.
2. No - Only recent history tool calls should be present. If RAG on old tool calls would be a thing, it should be defined under `searchOptions`. Personally I can't think of a use-case for this, unless it is for the model to see old examples of tool calls in cases where tools are very complex.

### PR DESCRIPTION
**Pull request by apostolisCodpal**
Addresses an issue where tool messages were not being properly paired in context.

- Modifies the order in which thread messages are retrieved, changing it to ascending.
- If the topmost message after `recentMessages` cutoff is an orphaned tool response, drops the message.

Fixes #38 

----

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.

### CODE REVIEW

File: src/client/index.ts [hunk 1]
```diff
@@ -454,17 +454,35 @@ export class Agent<AgentTools extends ToolSet> {
             cursor: null,
           },
           parentMessageId: args.parentMessageId,
-          order: "desc",
+          order: "asc",
```
Comment (ianmacartney) [inline src/client/index.ts]: A problem here is that this will now fetch the first N messages instead of the latest. Let's keep this "desc" and then keep the sorting below.

File: src/client/index.ts [hunk 2]
```diff
@@ -454,17 +454,35 @@ export class Agent<AgentTools extends ToolSet> {
...
           statuses: ["success"],
         }
       );
       contextMessages.push(...page.filter((m) => !included?.has(m._id)));
     }
-    return contextMessages
-      .sort((a, b) =>
-        a.order === b.order ? a.stepOrder - b.stepOrder : a.order - b.order
```
Comment (ianmacartney) [inline src/client/index.ts:465]: This should have been sorting them correctly already - I think the only bug was the orphaned messages

File: src/client/index.ts [hunk 3]
```diff
@@ -454,17 +454,35 @@ export class Agent<AgentTools extends ToolSet> {
...
-      .map((m) => deserializeMessage(m.message!));
+
+    // Sort the raw MessageDocs by order and stepOrder
+    const sortedDocs = contextMessages.sort((a, b) =>
+      a.order === b.order ? a.stepOrder - b.stepOrder : a.order - b.order
+    );
+
+    // When including tool calls, drop any orphaned tool messages at the start
+    if (opts.includeToolCalls) {
+      while (sortedDocs.length > 0 && sortedDocs[0].tool) {
```
Comment (ianmacartney) [inline src/client/index.ts]: maybe `&& sortedDocs[0]!.message?.role === "tool")`? The orphaned case is just when it starts with a tool response, ya?

**Review by ianmacartney — CHANGES_REQUESTED** [review]
let's keep "desc", but o.w. looking good

File: src/client/index.ts (hunk 2 above)
Comment (apostolisCodpal) [reply src/client/index.ts:465]: I didn't change the sorting.

Comment (Ale4224) [reply src/client/index.ts:465]: tool call and tool response have the same order and step order, so they get the original desc order

**Comment by ianmacartney** [comment]
Let’s reverse the list after we get it back in descending order OrdOrdering
by steps and step order is more of a safeguard against differentOrdering by
steps and step order is more of a safeguard against different agents
writingOrdering by steps and step order is more of a safeguard against
different agents writing to the same thread, if I remember correctly

**Comment by ianmacartney** [comment]
More generally the step order should probably be incremented between the to
call and result. It’s a bummer to not have that More generally the step
order should probably be incremented between the to call and result. It’s a
bummer to not have that ordering out of the box.

**Comment by ianmacartney** [comment]
Beyond dangling tool responses, if every step has the response and the call
reversed then it’s going to be trouble throughout

**Comment by ianmacartney** [comment]
I made the reversing change, thanks again for catching & cutting the PR!
